### ISSUE TITLE
NoSuchElementException: List is empty

### ISSUE THREAD

**Issue by lokesh-qa** [EMResearch/EvoMaster#137]
Trying to run evomaster for blackbox
java -jar evomaster.jar  --blackBox true --bbSwaggerUrl https://api.apis.guru/v2/specs/apis.guru/2.0.1/swagger.json  --outputFormat JAVA_JUNIT_4 --maxTime 30s

getting below warning and error
* EvoMaster version: 0.4.0

* There are 2 usable RESTful API endpoints defined in the schema configuration
15:51:21.319 [main] WARN  o.e.c.problem.rest.RestActionBuilder - Unhandled format 'url'
15:51:21.546 [main] WARN  o.e.c.problem.rest.RestActionBuilder - Unhandled format 'url'
15:51:21.552 [main] WARN  o.e.c.problem.rest.RestActionBuilder - Unhandled format 'url'
15:51:21.552 [main] WARN  o.e.c.problem.rest.RestActionBuilder - Unhandled format 'url'
* Starting to generate test cases
* [ERROR] EvoMaster process terminated abruptly. This is likely a bug in EvoMaster. Please copy&paste the following stacktrace, and create a new issue

stacktrace
java.util.NoSuchElementException: List is empty.
        at kotlin.collections.CollectionsKt___CollectionsKt.first(_Collections.kt:194)
        at org.evomaster.core.problem.rest.service.AbstractRestFitness.createInvocation(AbstractRestFitness.kt:423)
        at org.evomaster.core.problem.rest.service.AbstractRestFitness.handleRestCall(AbstractRestFitness.kt:297)
        at org.evomaster.core.problem.rest.service.BlackBoxRestFitness.doCalculateCoverage(BlackBoxRestFitness.kt:39)
        at org.evomaster.core.problem.rest.service.BlackBoxRestFitness.doCalculateCoverage(BlackBoxRestFitness.kt:14)
        at org.evomaster.core.search.service.FitnessFunction.calculateCoverage(FitnessFunction.kt:40)
        at org.evomaster.core.search.algorithms.RandomAlgorithm.search(RandomAlgorithm.kt:25)
        at org.evomaster.core.Main$Companion.run(Main.kt:275)
        at org.evomaster.core.Main$Companion.initAndRun(Main.kt:144)
        at org.evomaster.core.Main$Companion.main(Main.kt:71)
        at org.evomaster.core.Main.main(Main.kt)

**Comment by lokesh-qa** [comment]
$ java -version
java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)

**Comment by arcuri82** [comment]
Hi,
 thx for trying out EvoMaster. We were aware of this issue (it is related to parsing on OpenApi schemas), which should be already fixed in the current 0.4.1-SNAPSHOT. Please build `evomaster.jar` from master branch in Git.
We are going to make a new release with the fix, but that ll likely be sometime in January/February when some other features are completed as well

**Comment by lokesh-qa** [comment]
Thanks arcuri82.
It will be great to mention examples in read me which doesn't include OpenApi schemas.
Now I am trying to build from source.

Thanks.

**Comment by arcuri82** [comment]
Hi,
 a clarification: EvoMaster DOES work with OpenApi schemas (v2, not v3 yet though). The bug was related to when the `produces` info is on the top JSON document and not specified directly on each endpoint

**Comment by arcuri82** [comment]
today I made a new release, where the fix for this bug is present.

thx
