### ISSUE TITLE
IllegalArgumentException for an AWS api

### ISSUE THREAD

**Issue by JosephSe** [EMResearch/EvoMaster#146]
Command `java -jar core/target/evomaster.jar  --blackBox true --bbSwaggerUrl https://api.apis.guru/v2/specs/amazonaws.com/monitoring/2010-08-01/swagger.json  --outputFormat JAVA_JUNIT_4 --maxTime 30s`

```
java.lang.reflect.InvocationTargetException: invokedynamic: method=private final void org.evomaster.core.problem.rest.service.RestSampler.initialize(), target=org.evomaster.core.problem.rest.service.RestSampler@3a0d172f
	at com.netflix.governator.lifecycle.LifecycleMethods.methodInvoke(LifecycleMethods.java:316)
	at com.netflix.governator.lifecycle.LifecycleMethods.methodInvoke(LifecycleMethods.java:298)
	at com.netflix.governator.lifecycle.LifecycleManager.startInstance(LifecycleManager.java:266)
	at com.netflix.governator.lifecycle.LifecycleManager.add(LifecycleManager.java:175)
	at com.netflix.governator.guice.InternalLifecycleModule.onProvision(InternalLifecycleModule.java:81)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:120)
	at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:66)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:93)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:62)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
	at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:211)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:182)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:109)
	at com.google.inject.internal.InjectorImpl.createChildInjector(InjectorImpl.java:237)
	at com.netflix.governator.guice.LifecycleInjector.createChildInjector(LifecycleInjector.java:331)
	at com.netflix.governator.guice.LifecycleInjector.createInjector(LifecycleInjector.java:411)
	at com.netflix.governator.guice.LifecycleInjector.createInjector(LifecycleInjector.java:352)
	at org.evomaster.core.Main$Companion.init(Main.kt:224)
	at org.evomaster.core.Main$Companion.initAndRun(Main.kt:136)
	at org.evomaster.core.Main$Companion.main(Main.kt:69)
	at org.evomaster.core.Main.main(Main.kt)
Caused by: java.lang.IllegalArgumentException: The path contains invalid characters. Are you sure you didn't pass a full URI?
///#Action=DeleteAlarms
	at org.evomaster.core.problem.rest.RestPath.<init>(RestPath.kt:53)
	at org.evomaster.core.problem.rest.RestActionBuilder$Companion.addActionsFromSwagger(RestActionBuilder.kt:57)
	at org.evomaster.core.problem.rest.RestActionBuilder$Companion.addActionsFromSwagger$default(RestActionBuilder.kt:33)
	at org.evomaster.core.problem.rest.service.RestSampler.initForBlackBox(RestSampler.kt:129)
	at org.evomaster.core.problem.rest.service.RestSampler.initialize(RestSampler.kt:70)
	at com.netflix.governator.lifecycle.LifecycleMethods.methodInvoke(LifecycleMethods.java:313)
	... 26 common frames omitted
```

**Comment by arcuri82** [comment]
Hi,
  thanks for reporting this issue. Technically speaking, that OpenApi schema is invalid, as it uses # fragments in the path declarations. Eg,

```
"paths": {
    "/#Action=DeleteAlarms": {
      "get": {
        "description": "Deletes the specified alarms. You can delete up to 50 alarms in one operation. In the event of an error, no alarms are deleted.",
        "operationId": "GET DeleteAlarms",
        "parameters": [
```

It seems there is a [proposal](https://github.com/OAI/OpenAPI-Specification/issues/1635) for supporting # as part of the schemata in OpenApi.

Anyway, supporting # in EvoMaster would be pretty simple, so I will add it (hopefully soon...)
