### ISSUE TITLE
ClassCastException when processing swagger.json

### ISSUE THREAD

**Issue by JosephSe** [EMResearch/EvoMaster#147]
command `java -jar core/target/evomaster.jar  --blackBox true --bbSwaggerUrl https://petstore.swagger.io/v2/swagger.json --outputFormat JAVA_JUNIT_4 --maxTime 1h`

```
* EvoMaster version: 1.0.1-SNAPSHOT

java.lang.reflect.InvocationTargetException: invokedynamic: method=private final void org.evomaster.core.problem.rest.service.RestSampler.initialize(), target=org.evomaster.core.problem.rest.service.RestSampler@3a0d172f
	at com.netflix.governator.lifecycle.LifecycleMethods.methodInvoke(LifecycleMethods.java:316)
	at com.netflix.governator.lifecycle.LifecycleMethods.methodInvoke(LifecycleMethods.java:298)
	at com.netflix.governator.lifecycle.LifecycleManager.startInstance(LifecycleManager.java:266)
	at com.netflix.governator.lifecycle.LifecycleManager.add(LifecycleManager.java:175)
	at com.netflix.governator.guice.InternalLifecycleModule.onProvision(InternalLifecycleModule.java:81)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:120)
	at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:66)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:93)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:62)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
	at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:211)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:182)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:109)
	at com.google.inject.internal.InjectorImpl.createChildInjector(InjectorImpl.java:237)
	at com.netflix.governator.guice.LifecycleInjector.createChildInjector(LifecycleInjector.java:331)
	at com.netflix.governator.guice.LifecycleInjector.createInjector(LifecycleInjector.java:411)
	at com.netflix.governator.guice.LifecycleInjector.createInjector(LifecycleInjector.java:352)
	at org.evomaster.core.Main$Companion.init(Main.kt:224)
	at org.evomaster.core.Main$Companion.initAndRun(Main.kt:136)
	at org.evomaster.core.Main$Companion.main(Main.kt:69)
	at org.evomaster.core.Main.main(Main.kt)
Caused by: java.lang.ClassCastException: io.swagger.models.ArrayModel cannot be cast to io.swagger.models.ModelImpl
	at org.evomaster.core.problem.rest.RestActionBuilder$Companion.extractParams(RestActionBuilder.kt:224)
	at org.evomaster.core.problem.rest.RestActionBuilder$Companion.addActionsFromSwagger(RestActionBuilder.kt:62)
	at org.evomaster.core.problem.rest.RestActionBuilder$Companion.addActionsFromSwagger$default(RestActionBuilder.kt:33)
	at org.evomaster.core.problem.rest.service.RestSampler.initForBlackBox(RestSampler.kt:129)
	at org.evomaster.core.problem.rest.service.RestSampler.initialize(RestSampler.kt:70)
	at com.netflix.governator.lifecycle.LifecycleMethods.methodInvoke(LifecycleMethods.java:313)
	... 26 common frames omitted
```

**Comment by arcuri82** [comment]
Hi,
  thanks for reporting this bug. We are looking into it

**Comment by arcuri82** [comment]
the problem should now be fixed in the master branch

**Comment by arcuri82** [comment]
with new 1.0.1 release including the patch, this issue can be closed now
