### ISSUE TITLE
baseUrl must not be null

### ISSUE THREAD

**Issue by mado89** [EMResearch/EvoMaster#178]
Ciao Andrea,

When trying to run a whitebox test using the instructions the program ends up in an illegal state

`java.lang.IllegalStateException: baseUrl must not be null
	at org.evomaster.core.problem.rest.service.AbstractRestFitness.getBaseUrl(AbstractRestFitness.kt:277)
	at org.evomaster.core.problem.rest.service.AbstractRestFitness.getCookies(AbstractRestFitness.kt:566)
	at org.evomaster.core.problem.rest.service.RestFitness.doCalculateCoverage(RestFitness.kt:38)
	at org.evomaster.core.problem.rest.service.RestFitness.doCalculateCoverage(RestFitness.kt:22)
	at org.evomaster.core.search.service.FitnessFunction.calculateCoverage(FitnessFunction.kt:46)
	at org.evomaster.core.search.algorithms.MioAlgorithm.search(MioAlgorithm.kt:41)
	at org.evomaster.core.Main$Companion.run(Main.kt:280)
	at org.evomaster.core.Main$Companion.initAndRun(Main.kt:148)
	at org.evomaster.core.Main$Companion.main(Main.kt:72)
	at org.evomaster.core.Main.main(Main.kt)`

I assume that there is something wrong with my configuration. But how can I find out my mistake?

Thanks

**Comment by arcuri82** [comment]
even if it is a misconfiguration on your side, we should give a better error message :)  i ll fix it

are you doing Black-box or White-box testing? (the configurations to fix it would be different...)

**Comment by arcuri82** [comment]
i added some better error message.
however, it is weird, as it should not be possible to have "null" there.
how exactly did you run EvoMaster? eg, if you are doing White-Box testing, how is the implementation of your startSut()?
