### ISSUE TITLE
Building with Maven 3.6.3

### ISSUE THREAD

**Issue by bruceyy** [EMResearch/EvoMaster#198]
Hi

I have downloaded and starting having a play with the EvoMaster tool on the EvoMaster Benchmark projects.

I am on Ubuntu 20.04, using java 8.

Using EvoMaster 1.0.2 I can run in blackbox mode on the projects in EMB. However, I am running into some issues with whitebox mode. The drivers work, but the evomaster tool failed with the following ouput:

```
* 
 _____          ___  ___          _
|  ___|         |  \/  |         | |
| |____   _____ | .  . | __ _ ___| |_ ___ _ __
|  __\ \ / / _ \| |\/| |/ _` / __| __/ _ \ '__|
| |___\ V / (_) | |  | | (_| \__ \ ||  __/ |
\____/ \_/ \___/\_|  |_/\__,_|___/\__\___|_|

                    
* EvoMaster version: 1.0.2-SNAPSHOT
Jul 20, 2020 3:09:33 PM org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor aroundWriteTo
SEVERE: MessageBodyWriter not found for media type=application/json, type=class org.evomaster.client.java.controller.api.dto.SutRunDto, genericType=class org.evomaster.client.java.controller.api.dto.SutRunDto.
15:09:33.657 [main] WARN  o.e.c.r.service.RemoteController - Failed to connect to SUT: MessageBodyWriter not found for media type=application/json, type=class org.evomaster.client.java.controller.api.dto.SutRunDto, genericType=class org.evomaster.client.java.controller.api.dto.SutRunDto.
* [ERROR] ERROR in the Remote EvoMaster Driver: Failed to start the system under test
  Look at the logs of the EvoMaster Driver to help debugging this problem.

```

The logs from the driver show no indication of an error.

A little poking and i have come up with the following stack trace 

```
org.glassfish.jersey.message.internal.MessageBodyProviderNotFoundException: MessageBodyWriter not found for media type=application/json, type=class org.evomaster.client.java.controller.api.dto.SutRunDto, genericType=class org.evomaster.client.java.controller.api.dto.SutRunDto.
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.aroundWriteTo(WriterInterceptorExecutor.java:224)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:139)
	at org.glassfish.jersey.message.internal.MessageBodyFactory.writeTo(MessageBodyFactory.java:1115)
	at org.glassfish.jersey.client.ClientRequest.doWriteEntity(ClientRequest.java:503)
	at org.glassfish.jersey.client.ClientRequest.writeEntity(ClientRequest.java:485)
	at org.glassfish.jersey.client.internal.HttpUrlConnector._apply(HttpUrlConnector.java:360)
	at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:258)
	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:254)
	at org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$0(JerseyInvocation.java:736)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:205)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:390)
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:735)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:421)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.put(JerseyInvocation.java:310)
	at org.evomaster.core.remote.service.RemoteController$changeState$response$1.invoke(RemoteController.kt:221)
	at org.evomaster.core.remote.service.RemoteController$changeState$response$1.invoke(RemoteController.kt:33)
	at org.evomaster.core.remote.service.RemoteController.makeHttpCall(RemoteController.kt:83)
	at org.evomaster.core.remote.service.RemoteController.changeState(RemoteController.kt:217)
	at org.evomaster.core.remote.service.RemoteController.startSUT(RemoteController.kt:241)
	at org.evomaster.core.problem.rest.service.AbstractRestSampler.initialize(AbstractRestSampler.kt:63)
	at com.netflix.governator.lifecycle.LifecycleMethods.methodInvoke(LifecycleMethods.java:313)
	at com.netflix.governator.lifecycle.LifecycleMethods.methodInvoke(LifecycleMethods.java:298)
	at com.netflix.governator.lifecycle.LifecycleManager.startInstance(LifecycleManager.java:266)
	at com.netflix.governator.lifecycle.LifecycleManager.add(LifecycleManager.java:175)
	at com.netflix.governator.guice.InternalLifecycleModule.onProvision(InternalLifecycleModule.java:81)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:120)
	at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:66)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:93)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:62)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
	at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:213)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:184)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:111)
	at com.google.inject.internal.InjectorImpl.createChildInjector(InjectorImpl.java:246)
	at com.netflix.governator.guice.LifecycleInjector.createChildInjector(LifecycleInjector.java:331)
	at com.netflix.governator.guice.LifecycleInjector.createInjector(LifecycleInjector.java:411)
	at com.netflix.governator.guice.LifecycleInjector.createInjector(LifecycleInjector.java:352)
	at org.evomaster.core.Main$Companion.init(Main.kt:234)
	at org.evomaster.core.Main$Companion.initAndRun(Main.kt:139)
	at org.evomaster.core.Main$Companion.main(Main.kt:72)
	at org.evomaster.core.Main.main(Main.kt)

```

I can't see anything obvious with either the changeState function or SutRunDto.

Any advice would be appreciated - apologies in advance if this is a simple config issue on my side.

Thanks.

**Comment by arcuri82** [comment]
thanks for reporting this issue.

I have not seen it before, and I cannot reproduce it. So, I ll need some more info to investigate it:

* output of `java -version`
* output of `mvn --version`
* name of the project in EMB you are trying out
* terminal command-line you are using to run `evomaster.jar`
* does the same problem appear if you use `evomaster.jar` version `1.0.2` (downloaded from GitHub) instead of locally built `1.0.2-SNAPSHOT`?

**Comment by bruceyy** [comment]
```
mvn --version
Apache Maven 3.6.3
Maven home: /usr/share/maven
Java version: 1.8.0_252, vendor: Private Build, runtime: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: en_GB, platform encoding: UTF-8
OS name: "linux", version: "5.4.0-40-generic", arch: "amd64", family: "unix"
```

```
java -version
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-8u252-b09-1ubuntu1-b09)
OpenJDK 64-Bit Server VM (build 25.252-b09, mixed mode)
```

I have tried scout-api and features-service.

running `java -jar core/target/evomaster.jar`

I have downloaded the v1.0.1 jar and that works, whereas my locally built 1.0.1 throws the same error as above.


thanks

**Comment by arcuri82** [comment]
hmmm... that is really weird. Usually, that error message would be present when Jackson support is not provided to Jersey. But that is explicitly done  in the pom file with:

```
            <dependency>
                <groupId>org.glassfish.jersey.media</groupId>
                <artifactId>jersey-media-json-jackson</artifactId>
                <version>${jersey.version}</version>
            </dependency>
```

can you check if those files end up in the generated jar? eg.:

```
cd core/target/
unzip evomaster.jar -d foo
ls foo/org/glassfish/jersey/jackson/
```

furthermore, which `mvn` command did you use when building locally?

thanks

**Comment by arcuri82** [comment]
might also be worthy to delete the files from:
`~/.m2/repository/org/glassfish/jersey/media/`
to force Maven to re-download them (in case there was some file corruption issue there...)

**Comment by bruceyy** [comment]
Yup files are in the generated jar

Command used :  `mvn clean install -DskipTests`

I have wiped my maven local repo and still getting the error

**Comment by bruceyy** [comment]
I have managed to build from source v1.0.1 on a different machine and copy it over, run it, and its working (woohoo). 

It would seem there is something quirky going during the compilation process - thanks for your help and I will update the issue if i find out exactly what it was causing the error

**Comment by arcuri82** [comment]
thanks for the update.

wondering if it is something related to the version of Maven... you wrote you used 3.6.3, whereas on my machine I still have an older 3.5.0

What is the Maven version in the other machine you managed to successfully build?

**Comment by bruceyy** [comment]
yeah you got it - switched to maven version 3.5.0 and can successfully build and run v1.0.1 :)

**Comment by arcuri82** [comment]
thanks for checking this out.
i ll need to look into why it fails with 3.6.3

**Comment by arcuri82** [comment]
updating maven-assembly plugin seems to fix the issue
