### ISSUE TITLE
Error Generate Test Case

### ISSUE THREAD

**Issue by marshallia** [EMResearch/EvoMaster#237]
Hi @arcuri82 ,
I try to create test cases using evomaster for spring boot application build using Maven. the program doesn't use any database.  After I run the evo driver from the IDE, I run the evomaster.jar and got an error. Here the command that I use
`java -jar evomaster.jar --maxTime 60s --outputFolder "Evo"`
And here my EvoMaster Driver
`
import org.evomaster.client.java.controller.EmbeddedSutController;
import org.evomaster.client.java.controller.InstrumentedSutStarter;
import org.evomaster.client.java.controller.api.dto.AuthenticationDto;
import org.evomaster.client.java.controller.api.dto.SutInfoDto;
import org.evomaster.client.java.controller.problem.ProblemInfo;
import org.evomaster.client.java.controller.problem.RestProblem;
import org.springframework.boot.SpringApplication;
import org.springframework.context.ConfigurableApplicationContext;
import java.sql.Connection;
import java.util.List;
import java.util.Map;
public class EvoMasterController extends EmbeddedSutController {
    private ConfigurableApplicationContext ctx;

    public static void main(String[] args) {
        int port = 40100;
        EvoMasterController controller = new EvoMasterController(port);
        InstrumentedSutStarter starter = new InstrumentedSutStarter(controller);
        starter.start();
    }
    public EvoMasterController(int port) {
        this.port = port;
    }

    @Override
    public boolean isSutRunning() {
        return ctx !=null && ctx.isRunning();
    }

    @Override
    public List<AuthenticationDto> getInfoForAuthentication() {
        return null;
    }

    @Override
    public Connection getConnection() {
        return null;
    }

    @Override
    public String getDatabaseDriverName() {
        return null;
    }

    @Override
    public ProblemInfo getProblemInfo() {
        return new RestProblem(
                "http://localhost:" + getSutPort() + "/swagger.json",
                null
        );
    }

    @Override
    public SutInfoDto.OutputFormat getPreferredOutputFormat() {
        return SutInfoDto.OutputFormat.JAVA_JUNIT_4;
    }

    @Override
    public String getPackagePrefixesToCover() {
        return "org.javiermf.features.";
    }

    @Override
    public String startSut() {
        ctx = SpringApplication.run(DemoApplication.class, new String[]{"--server.port=0"});
        return "http://localhost:"+getSutPort();
    }

    @Override
    public void stopSut() {
        ctx.stop();
    }

    @Override
    public void resetStateOfSUT() {

    }
    protected int getSutPort(){
        return (Integer)((Map) ctx.getEnvironment().getPropertySources().get("server.port").getSource())
                .get("local.server.port");
    }
}`
And here is the error message 
![Screenshot from 2021-01-18 17-01-42](https://user-images.githubusercontent.com/12694360/104893823-dd7bed00-59ae-11eb-8e41-8a5af5641a6c.png)

**Comment by arcuri82** [comment]
this seems a bug in the `SchemaOracle` code

@bogdanmarculescu  can you please look at it? is there any command-line option to deactivate them?

**Comment by bogdanmarculescu** [comment]
Yes, the problem is in handling the SchemaOracle. That is still work in progress, so testing for it is not great. I've pushed a quick fix that just deactivates it.

**Comment by arcuri82** [comment]
@marshallia to add to this: from the screenshot, i see you used version 1.1.0. can you try to build evomaster.jar from the repository, and see if you still see the same problem.
otherwise, is the project you working on open-source by any chance?

**Comment by marshallia** [comment]
the jar works fine now. I clone the revision done by @bogdanmarculescu and build it. But when I try to do a test on CRUD test using h2 database I found another bug. 
`java.lang.reflect.InvocationTargetException: invokedynamic: method=public void org.evomaster.core.problem.rest.service.AbstractRestSampler.initialize(), target=org.evomaster.core.problem.rest.service.RestSampler@f001896
	at com.netflix.governator.lifecycle.LifecycleMethods.methodInvoke(LifecycleMethods.java:316)
	at com.netflix.governator.lifecycle.LifecycleMethods.methodInvoke(LifecycleMethods.java:298)
	at com.netflix.governator.lifecycle.LifecycleManager.startInstance(LifecycleManager.java:266)
	at com.netflix.governator.lifecycle.LifecycleManager.add(LifecycleManager.java:175)
	at com.netflix.governator.guice.InternalLifecycleModule.onProvision(InternalLifecycleModule.java:81)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:120)
	at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:66)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:93)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
	at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:62)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
	at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:213)
	at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:184)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:111)
	at com.google.inject.internal.InjectorImpl.createChildInjector(InjectorImpl.java:246)
	at com.netflix.governator.guice.LifecycleInjector.createChildInjector(LifecycleInjector.java:331)
	at com.netflix.governator.guice.LifecycleInjector.createInjector(LifecycleInjector.java:411)
	at com.netflix.governator.guice.LifecycleInjector.createInjector(LifecycleInjector.java:352)
	at org.evomaster.core.Main$Companion.init(Main.kt:242)
	at org.evomaster.core.Main$Companion.initAndRun(Main.kt:140)
	at org.evomaster.core.Main$Companion.main(Main.kt:73)
	at org.evomaster.core.Main.main(Main.kt)
Caused by: java.lang.IllegalStateException: Failed to connect to http://localhost:8090/v2/api-docs
	at org.evomaster.core.problem.rest.OpenApiAccess.connectToServer(OpenApiAccess.kt:57)
	at org.evomaster.core.problem.rest.OpenApiAccess.getOpenAPI(OpenApiAccess.kt:18)
	at org.evomaster.core.problem.rest.service.AbstractRestSampler.initialize(AbstractRestSampler.kt:75)
	at com.netflix.governator.lifecycle.LifecycleMethods.methodInvoke(LifecycleMethods.java:313)
	... 26 common frames omitted
`
Here is my driver, 
`public class EvoMasterController extends EmbeddedSutController {
    private ConfigurableApplicationContext ctx;
    private final int port;
    private Connection connection;

    public static void main(String[] args) {
        int port = 40100;
        EvoMasterController controller = new EvoMasterController();
        InstrumentedSutStarter starter = new InstrumentedSutStarter(controller);
        starter.start();
    }
    public EvoMasterController() {
        this.port = 40100;
    }

    @Override
    public boolean isSutRunning() {
        return ctx !=null && ctx.isRunning();
    }

    @Override
    public List<AuthenticationDto> getInfoForAuthentication() {
        return null;
    }

    @Override
    public Connection getConnection() {
        return null;
    }

    @Override
    public String getDatabaseDriverName() {
        return null;
    }

    @Override
    public ProblemInfo getProblemInfo() {
        return new RestProblem(
                "http://localhost:8090/v2/api-docs",
                null
        );
    }

    @Override
    public SutInfoDto.OutputFormat getPreferredOutputFormat() {
        return SutInfoDto.OutputFormat.JAVA_JUNIT_4;
    }

    @Override
    public String getPackagePrefixesToCover() {
        return "org.javiermf.features.";
    }

    @Override
    public String startSut() {
        ctx = SpringApplication.run(DemoApplication.class, new String[]{
                "--server.port=0",
                "--spring.datasource.url=jdbc:h2:mem:testdb;",
                "--spring.datasource.driver-class-name=org.h2.Driver",
                "--spring.jpa.database-platform=org.hibernate.dialect.H2Dialect",
                "--spring.datasource.username=sa",
                "--spring.datasource.password=password",
                "--spring.cache.type=NONE"
        });
        JdbcTemplate jdbc = ctx.getBean(JdbcTemplate.class);
        try {
            connection = jdbc.getDataSource().getConnection();
        } catch (SQLException throwables) {
            throwables.printStackTrace();
        }
        return "http://localhost:8090";
    }

    @Override
    public void stopSut() {
        ctx.stop();
    }

    @Override
    public void resetStateOfSUT() {
        DbCleaner.clearDatabase_H2(connection);
    }
    protected int getSutPort(){
        return (Integer)((Map) ctx.getEnvironment().getPropertySources().get("server.port").getSource())
                .get("local.server.port");

    }
}
`
Is the driver written correctly? thank you

**Comment by arcuri82** [comment]
hi,
  you have a problem in the driver.  you start the server with `--server.port=0`, which binds it on an ephemeral port. however, you hard-coded `8090` in 2 places instead of using ` getSutPort()`

**Comment by marshallia** [comment]
Thank you for your answer @arcuri82 . the test generated from EvoMaster is worked fine now. All the test cases are passed
