### ISSUE TITLE
Error - gitlab testing with blackbox mode

### ISSUE THREAD

**Issue by codingsoo** [EMResearch/EvoMaster#249]
Hi, thank you for this amazing tool!
I used blackbox mode with official gitlab swagger file (https://axil.gitlab.io/swaggerapi/) and the right version(gitlab-ee:8.15.7-ee.0), but got an following error.

Command: java -jar evomaster.jar --blackBox true --bbSwaggerUrl https://axil.gitlab.io/swaggerapi/static/swagger.json --outputFormat JAVA_JUNIT_4 --maxTime 30s

* ?[31m[ERROR] ?[0m?[33mEvoMaster process terminated abruptly. This is likely a bug in EvoMaster. Please copy&paste the following stacktrace, and create a new issue on ?[34mhttps://github.com/EMResearch/EvoMaster/issues?[0m?[0m
java.lang.reflect.InvocationTargetException: invokedynamic: method=public void org.evomaster.core.problem.rest.service.AbstractRestSampler.initialize(), target=org.evomaster.core.problem.rest.service.RestSampler@1951b871
        at com.netflix.governator.lifecycle.LifecycleMethods.methodInvoke(LifecycleMethods.java:316)
        at com.netflix.governator.lifecycle.LifecycleMethods.methodInvoke(LifecycleMethods.java:298)
        at com.netflix.governator.lifecycle.LifecycleManager.startInstance(LifecycleManager.java:266)
        at com.netflix.governator.lifecycle.LifecycleManager.add(LifecycleManager.java:175)
        at com.netflix.governator.guice.InternalLifecycleModule.onProvision(InternalLifecycleModule.java:81)
        at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:120)
        at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:66)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:93)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
        at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:62)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
        at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:213)
        at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:184)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:111)
        at com.google.inject.internal.InjectorImpl.createChildInjector(InjectorImpl.java:246)
        at com.netflix.governator.guice.LifecycleInjector.createChildInjector(LifecycleInjector.java:331)
        at com.netflix.governator.guice.LifecycleInjector.createInjector(LifecycleInjector.java:411)
        at com.netflix.governator.guice.LifecycleInjector.createInjector(LifecycleInjector.java:352)
        at org.evomaster.core.Main$Companion.init(Main.kt:236)
        at org.evomaster.core.Main$Companion.initAndRun(Main.kt:139)
        at org.evomaster.core.Main$Companion.main(Main.kt:72)
        at org.evomaster.core.Main.main(Main.kt)
Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
        at java.lang.Integer.compareTo(Unknown Source)
        at java.util.ComparableTimSort.countRunAndMakeAscending(Unknown Source)
        at java.util.ComparableTimSort.sort(Unknown Source)
        at java.util.Arrays.sort(Unknown Source)
        at kotlin.collections.ArraysKt___ArraysJvmKt.sort(_ArraysJvm.kt:1876)
        at kotlin.collections.CollectionsKt___CollectionsKt.sorted(_Collections.kt:945)
        at org.evomaster.core.search.gene.EnumGene.<init>(EnumGene.kt:45)
        at org.evomaster.core.search.gene.EnumGene.<init>(EnumGene.kt:21)
        at org.evomaster.core.problem.rest.RestActionBuilderV3.getGene(RestActionBuilderV3.kt:385)
        at org.evomaster.core.problem.rest.RestActionBuilderV3.createObjectGene(RestActionBuilderV3.kt:492)
        at org.evomaster.core.problem.rest.RestActionBuilderV3.getGene(RestActionBuilderV3.kt:477)
        at org.evomaster.core.problem.rest.RestActionBuilderV3.getGene$default(RestActionBuilderV3.kt:347)
        at org.evomaster.core.problem.rest.RestActionBuilderV3.handleBodyPayload(RestActionBuilderV3.kt:322)
        at org.evomaster.core.problem.rest.RestActionBuilderV3.extractParams(RestActionBuilderV3.kt:238)
        at org.evomaster.core.problem.rest.RestActionBuilderV3.handleOperation(RestActionBuilderV3.kt:158)
        at org.evomaster.core.problem.rest.RestActionBuilderV3.addActionsFromSwagger(RestActionBuilderV3.kt:104)
        at org.evomaster.core.problem.rest.RestActionBuilderV3.addActionsFromSwagger$default(RestActionBuilderV3.kt:51)
        at org.evomaster.core.problem.rest.service.AbstractRestSampler.initForBlackBox(AbstractRestSampler.kt:147)
        at org.evomaster.core.problem.rest.service.AbstractRestSampler.initialize(AbstractRestSampler.kt:57)
        at com.netflix.governator.lifecycle.LifecycleMethods.methodInvoke(LifecycleMethods.java:313)
        ... 26 common frames omitted

**Comment by arcuri82** [comment]
Hi,
 thx for reporting this bug. made a fix in the "master" branch, and now should not fail. u will need to build `evomaster.jar` manually. not sure when we are making a new release (in some weeks i guess)

**Comment by arcuri82** [comment]
this should now be fixed in the new 1.2.0 release. if not, please open a new issue
