### ISSUE TITLE
error message

### ISSUE THREAD

**Issue by webrollygoal** [EMResearch/EvoMaster#251]
11:50:48.012 [main] WARN  o.e.c.r.service.RemoteController - Failed to change running state of the SUT. HTTP status 500. Error: 'java.lang.NullPointerException'
* ?[31m[ERROR] ?[0m?[33mERROR in the Remote EvoMaster Driver: Failed to start the system under test
  Look at the logs of the EvoMaster Driver to help debugging this problem.?[0m

**Comment by arcuri82** [comment]
hi,
 literally: `Look at the logs of the EvoMaster Driver to help debugging this problem`.
what is the error message there? likely it is a misconfiguration in the driver class

**Comment by webrollygoal** [comment]
ERROR - No qualifying bean of type 'org.springframework.jdbc.core.JdbcTemplate' available
org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.springframework.jdbc.core.JdbcTemplate' available
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:352)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:339)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1094)
	at org.example.EMDriver.startSut(EMDriver.java:72)
	at org.evomaster.client.java.controller.internal.EMController.runSut(EMController.java:210)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at shaded.org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)
	at shaded.org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124)
	at shaded.org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167)
	at shaded.org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:176)
	at shaded.org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79)
	at shaded.org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:469)
	at shaded.org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:391)
	at shaded.org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:80)
	at shaded.org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:253)
	at shaded.org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
	at shaded.org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
	at shaded.org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at shaded.org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at shaded.org.glassfish.jersey.internal.Errors.process(Errors.java:244)
	at shaded.org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
	at shaded.org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:232)
	at shaded.org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680)
	at shaded.org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:392)
	at shaded.org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
	at shaded.org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:365)
	at shaded.org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:318)
	at shaded.org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
	at shaded.org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:763)
	at shaded.org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:551)
	at shaded.org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at shaded.org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1369)
	at shaded.org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at shaded.org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:489)
	at shaded.org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at shaded.org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1284)
	at shaded.org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at shaded.org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at shaded.org.eclipse.jetty.server.Server.handle(Server.java:501)
	at shaded.org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
	at shaded.org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:556)
	at shaded.org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
	at shaded.org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)
	at shaded.org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at shaded.org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at shaded.org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at shaded.org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
	at shaded.org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
	at shaded.org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
	at shaded.org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:135)
	at shaded.org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
	at shaded.org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
	at java.lang.Thread.run(Thread.java:748)

**Comment by arcuri82** [comment]
what is the code of your `org.example.EMDriver.startSut(EMDriver.java:72)`? 
looks like you are trying to get JDBC bean for the DB connection, but that is not available in your application? do you use a DB in your application?

**Comment by webrollygoal** [comment]
JdbcTemplate jdbc = ctx.getBean(JdbcTemplate.class);
        try {
            connection = jdbc.getDataSource().getConnection();
        } catch (SQLException throwables) {
            throwables.printStackTrace();
        }

**Comment by webrollygoal** [comment]
public void resetStateOfSUT() {
        DbCleaner.clearDatabase_H2(connection);
    }  if I delete jdbc template what changes should I do here

**Comment by arcuri82** [comment]
if you do not use a database (H2 in this case), then just leave `resetStateOfSUT` empty

**Comment by webrollygoal** [comment]
Sir can we have a short zoom call I want to extend this work with evomaster  and want to understand the working of evomaster as well 
also, sir, I'm getting this output can you please explain the parts of this output
Going to save 22 tests to src/test/java
* Evaluated tests: 99567
* Evaluated actions: 112024
* Needed budget: 3%
* Passed time (seconds): 600
* Execution time per test (ms): Avg=4.80 , min=0.00 , max=1465.00
* Computation overhead between tests (ms): Avg=1.22 , min=0.00 , max=107.00
* Covered targets (lines, branches, faults, etc.): 69
* Potential faults: 26
* Bytecode line coverage: NaN% (0 out of 0 in 0 units/classes)
* EvoMaster process has completed successfully


What is evaluated tests
what is evaluated actions  etc
