### ISSUE TITLE
dependency problem

### ISSUE THREAD

**Issue by huangzewen** [EMResearch/EvoMaster#3]
Hi,
While I was compile EMB-master using command:
mvn -P '!withEmbedded' clean package -DskipTests
OR
mvn -P !withEmbedded clean package -DskipTests
I failed. Following is the error info:
[ERROR] Failed to execute goal on project persistence: Could not resolve depende
ncies for project org.devgateway.ocvn:persistence:jar:1.1.1-SNAPSHOT: Failed to
collect dependencies at dozer-hibernate-model:dozer-hibernate-model:jar:0.3.5-06
032016: Failed to read artifact descriptor for dozer-hibernate-model:dozer-hiber
nate-model:jar:0.3.5-06032016: Could not transfer artifact dozer-hibernate-model
:dozer-hibernate-model:pom:0.3.5-06032016 from/to OCVN (http://artifactory.ampde
v.net/artifactory/ocvn/): Connect to artifactory.ampdev.net:80 [artifactory.ampd
ev.net/4.79.228.117] failed: Connection timed out: connect -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyReso
lutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command

[ERROR] mvn -rf :persistence

**Comment by huangzewen** [comment]
While I run EmbeddedEvoMasterController.java, I failed. Following is the Exception. I thought that something wrong with dependency problem I proposed yesterday （the previous comment）. Could you please help me repreduce your experiment results. Thanks.

Exception in thread "main" java.lang.ExceptionInInitializerError
at em.embedded.org.javiermf.features.EmbeddedEvoMasterController.main(EmbeddedEvoMasterController.java:33)
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
at shaded.com.ea.agentloader.AgentLoader$1.loadAgent(AgentLoader.java:244)
at shaded.com.ea.agentloader.AgentLoader.loadAgent(AgentLoader.java:77)
at shaded.com.ea.agentloader.AgentLoader.loadAgentClass(AgentLoader.java:148)
at shaded.com.ea.agentloader.AgentLoader.loadAgentClass(AgentLoader.java:102)
at org.evomaster.clientJava.controller.InstrumentedSutStarter.(InstrumentedSutStarter.java:27)
... 1 more
Caused by: java.lang.reflect.InvocationTargetException
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at shaded.com.ea.agentloader.AgentLoader$1.loadAgent(AgentLoader.java:240)
... 5 more
Caused by: java.lang.RuntimeException: java.io.IOException: Can not attach to current VM
at shaded.com.ea.agentloader.AgentLoaderHotSpot.getVirtualMachine(AgentLoaderHotSpot.java:90)
at shaded.com.ea.agentloader.AgentLoaderHotSpot.loadAgent(AgentLoaderHotSpot.java:56)
... 10 more
Caused by: java.io.IOException: Can not attach to current VM
at jdk.attach/sun.tools.attach.HotSpotVirtualMachine.(HotSpotVirtualMachine.java:75)
at jdk.attach/sun.tools.attach.VirtualMachineImpl.(VirtualMachineImpl.java:48)
at jdk.attach/sun.tools.attach.AttachProviderImpl.attachVirtualMachine(AttachProviderImpl.java:69)
at jdk.attach/com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:207)
at shaded.com.ea.agentloader.AgentLoaderHotSpot.getVirtualMachine(AgentLoaderHotSpot.java:86)
... 11 more

**Comment by arcuri82** [comment]
Hi,
  regarding first problem: looks like a connection issue with a remove Maven server. Do you still have the same issue now? From my machine(s) I have no problem connecting to it. Could it be a firewall issue on your side?

on second problem: did the problem happen just once, or all the times? Are you by any chance using Java 9?

**Comment by arcuri82** [comment]
Hi,
  indeed that part was not explained. I added some documentation in the Readme at:

https://github.com/EMResearch/EMB

**Comment by huangzewen** [comment]
Oh, I succeeded. Thanks for your help.

**Comment by arcuri82** [comment]
glad to hear it ;)
