### ISSUE TITLE
Error encountered when running EvoMaster with math.tools Numbers API

### ISSUE THREAD

**Issue by nayaksnigdha** [EMResearch/EvoMaster#316]
Hello EvoMaster team,

I am getting an exception when running EvoMaster tool in blackbox mode when testing math.tools API. (http://api.math.tools)

**Command Used :**
java -jar evomaster.jar  --blackBox true --bbTargetUrl http://api.math.tools --outputFormat JAVA_JUNIT_4 --maxTime 3000s --bbSwaggerUrl https://api.apis.guru/v2/specs/nexmo.com/numbers/1.0.20/openapi.json

**Stack Trace :** 

 EvoMaster version: 1.1.0
10:29:25.212 [main] WARN  o.e.c.p.rest.RestActionBuilderV3 - Operation getOwnedNumbers has 5 repeated parameters
* [31m[ERROR] [0m[33mEvoMaster process terminated abruptly. This is likely a bug in EvoMaster. Please copy&paste the following stacktrace, and create a new issue on [34mhttps://github.com/EMResearch/EvoMaster/issues[0m[0m
java.lang.reflect.InvocationTargetException: invokedynamic: method=public void org.evomaster.core.problem.rest.service.AbstractRestSampler.initialize(), target=org.evomaster.core.problem.rest.service.RestSampler@3d3ba765
        at com.netflix.governator.lifecycle.LifecycleMethods.methodInvoke(LifecycleMethods.java:316)
        at com.netflix.governator.lifecycle.LifecycleMethods.methodInvoke(LifecycleMethods.java:298)
        at com.netflix.governator.lifecycle.LifecycleManager.startInstance(LifecycleManager.java:266)
        at com.netflix.governator.lifecycle.LifecycleManager.add(LifecycleManager.java:175)
        at com.netflix.governator.guice.InternalLifecycleModule.onProvision(InternalLifecycleModule.java:81)
        at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:120)
        at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:66)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:93)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
        at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:62)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
        at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:213)
        at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:184)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:111)
        at com.google.inject.internal.InjectorImpl.createChildInjector(InjectorImpl.java:246)
        at com.netflix.governator.guice.LifecycleInjector.createChildInjector(LifecycleInjector.java:331)
        at com.netflix.governator.guice.LifecycleInjector.createInjector(LifecycleInjector.java:411)
        at com.netflix.governator.guice.LifecycleInjector.createInjector(LifecycleInjector.java:352)
        at org.evomaster.core.Main$Companion.init(Main.kt:236)
        at org.evomaster.core.Main$Companion.initAndRun(Main.kt:139)
        at org.evomaster.core.Main$Companion.main(Main.kt:72)
        at org.evomaster.core.Main.main(Main.kt)
Caused by: java.lang.IllegalStateException: p.schema must not be null
        at org.evomaster.core.problem.rest.RestActionBuilderV3.extractParams(RestActionBuilderV3.kt:211)
        at org.evomaster.core.problem.rest.RestActionBuilderV3.handleOperation(RestActionBuilderV3.kt:158)
        at org.evomaster.core.problem.rest.RestActionBuilderV3.addActionsFromSwagger(RestActionBuilderV3.kt:103)
        at org.evomaster.core.problem.rest.RestActionBuilderV3.addActionsFromSwagger$default(RestActionBuilderV3.kt:51)
        at org.evomaster.core.problem.rest.service.AbstractRestSampler.initForBlackBox(AbstractRestSampler.kt:147)
        at org.evomaster.core.problem.rest.service.AbstractRestSampler.initialize(AbstractRestSampler.kt:57)
        at com.netflix.governator.lifecycle.LifecycleMethods.methodInvoke(LifecycleMethods.java:313)
        ... 26 common frames omitted

**Comment by arcuri82** [comment]
hi.
  thanks for reporting this issue. we are looking into it

**Comment by arcuri82** [comment]
issue is now fixed in the master branch... will be part of next release (likely sometime in June)

**Comment by arcuri82** [comment]
this should now be fixed in the new 1.2.0 release. if not, please open a new issue
