### ISSUE TITLE
Black-Box Testing Authorization error

### ISSUE THREAD

**Issue by jiaxian-lin** [EMResearch/EvoMaster#425]
I use EvoMaster to test a local service and get this Error, I guess this may cause by Authorization

            at com.netflix.governator.lifecycle.LifecycleMethods.methodInvoke(LifecycleMethods.java:316)
            at com.netflix.governator.lifecycle.LifecycleMethods.methodInvoke(LifecycleMethods.java:298)
            at com.netflix.governator.lifecycle.LifecycleManager.startInstance(LifecycleManager.java:266)
            at com.netflix.governator.lifecycle.LifecycleManager.add(LifecycleManager.java:175)
            at com.netflix.governator.guice.InternalLifecycleModule.onProvision(InternalLifecycleModule.java:81)
            at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:117)
            at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:66)
            at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:93)
            at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:296)
            at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
            at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169)
            at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
            at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:60)
            at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
            at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169)
            at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
            at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:213)
            at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:186)
            at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:113)
            at com.google.inject.internal.InjectorImpl.createChildInjector(InjectorImpl.java:239)
            at com.netflix.governator.guice.LifecycleInjector.createChildInjector(LifecycleInjector.java:331)
            at com.netflix.governator.guice.LifecycleInjector.createInjector(LifecycleInjector.java:411)
            at com.netflix.governator.guice.LifecycleInjector.createInjector(LifecycleInjector.java:352)
            at org.evomaster.core.Main$Companion.init(Main.kt:284)
            at org.evomaster.core.Main$Companion.initAndRun(Main.kt:138)
            at org.evomaster.core.Main$Companion.main(Main.kt:71)
            at org.evomaster.core.Main.main(Main.kt)
      Caused by: java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 0
            at java.base/java.lang.String.checkBoundsBeginEnd(String.java:4601)
            at java.base/java.lang.String.substring(String.java:2704)
            at org.evomaster.core.problem.httpws.service.HttpWsSampler.addAuthFromConfig(HttpWsSampler.kt:82)
            at org.evomaster.core.problem.rest.service.AbstractRestSampler.initForBlackBox(AbstractRestSampler.kt:165)
            at org.evomaster.core.problem.rest.service.AbstractRestSampler.initialize(AbstractRestSampler.kt:45)
            at com.netflix.governator.lifecycle.LifecycleMethods.methodInvoke(LifecycleMethods.java:313)
            ... 26 common frames omitted

**Comment by jiaxian-lin** [comment]
this is my command:

     java -jar evomaster.jar --blackBox true --bbSwaggerUrl file:///file_path --outputFormat JAVA_JUNIT_4 --maxTime 30s --bbTargetUrl http://192.168.112.162 --header0 'Authorization:Bearer _token_'

**Comment by arcuri82** [comment]
thx for reporting this bug. until we make a fix, you can try to use this workaround, ie, add: `--header1 'a:a' --header2 'b:b'`

**Comment by arcuri82** [comment]
This issue should now be fixed in the new 1.4.0 release
