### ISSUE TITLE
Regex "pattern" constraint error  

### ISSUE THREAD

**Issue by lin2020** [EMResearch/EvoMaster#428]
``Hi,
I'm trying evomaster on my project, I run evomaster.jar which is downloaded from
[link](https://github.com/EMResearch/EvoMaster/releases/download/v1.3.0/evomaster.jar.zip) with the command

> java -jar evomaster.jar --blackBox true --bbSwaggerUrl [swagger-url] --outputFormat JAVA_JUNIT_4 --maxTime 30s

and get the following error

`
java.lang.reflect.InvocationTargetException: invokedynamic: method=public void org.evomaster.core.problem.rest.service.AbstractRestSampler.initialize(), target=org.evomaster.core.problem.rest.service.RestSampler@25748410
        at com.netflix.governator.lifecycle.LifecycleMethods.methodInvoke(LifecycleMethods.java:316)
        at com.netflix.governator.lifecycle.LifecycleMethods.methodInvoke(LifecycleMethods.java:298)
        at com.netflix.governator.lifecycle.LifecycleManager.startInstance(LifecycleManager.java:266)
        at com.netflix.governator.lifecycle.LifecycleManager.add(LifecycleManager.java:175)
        at com.netflix.governator.guice.InternalLifecycleModule.onProvision(InternalLifecycleModule.java:81)
        at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:117)
        at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:66)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:93)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:296)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
        at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:60)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
        at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:213)
        at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:186)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:113)
        at com.google.inject.internal.InjectorImpl.createChildInjector(InjectorImpl.java:239)
        at com.netflix.governator.guice.LifecycleInjector.createChildInjector(LifecycleInjector.java:331)
        at com.netflix.governator.guice.LifecycleInjector.createInjector(LifecycleInjector.java:411)
        at com.netflix.governator.guice.LifecycleInjector.createInjector(LifecycleInjector.java:352)
        at org.evomaster.core.Main$Companion.init(Main.kt:284)
        at org.evomaster.core.Main$Companion.initAndRun(Main.kt:138)
        at org.evomaster.core.Main$Companion.main(Main.kt:71)
        at org.evomaster.core.Main.main(Main.kt)
Caused by: java.lang.IllegalArgumentException: Start '!' is after end ' '
        at org.evomaster.core.search.service.Randomness.nextChar(Randomness.kt:313)
        at org.evomaster.core.search.gene.regex.CharacterRangeRxGene.randomize(CharacterRangeRxGene.kt:58)
        at org.evomaster.core.search.gene.regex.QuantifierRxGene.addNewAtom(QuantifierRxGene.kt:171)
        at org.evomaster.core.search.gene.regex.QuantifierRxGene.randomize(QuantifierRxGene.kt:107)
        at org.evomaster.core.search.gene.regex.DisjunctionRxGene.randomize(DisjunctionRxGene.kt:56)
        at org.evomaster.core.search.gene.regex.DisjunctionListRxGene.randomize(DisjunctionListRxGene.kt:47)
        at org.evomaster.core.search.gene.regex.RegexGene.randomize(RegexGene.kt:29)
        at org.evomaster.core.search.gene.OptionalGene.randomize(OptionalGene.kt:89)
        at org.evomaster.core.search.gene.ObjectGene.randomize(ObjectGene.kt:88)
        at org.evomaster.core.search.gene.Gene.randomize$default(Gene.kt:75)
        at org.evomaster.core.problem.httpws.service.HttpWsAction.randomize(HttpWsAction.kt:17)
        at org.evomaster.core.problem.rest.RestCallAction.randomize(RestCallAction.kt:206)
        at org.evomaster.core.search.Action.randomize$default(Action.kt:41)
        at org.evomaster.core.problem.httpws.service.HttpWsSampler.randomizeActionGenes(HttpWsSampler.kt:43)
        at org.evomaster.core.problem.httpws.service.HttpWsSampler.randomizeActionGenes$default(HttpWsSampler.kt:41)
        at org.evomaster.core.problem.rest.service.RestSampler.createSingleCallOnEachEndpoint(RestSampler.kt:408)
        at org.evomaster.core.problem.rest.service.RestSampler.customizeAdHocInitialIndividuals(RestSampler.kt:395)
        at org.evomaster.core.problem.rest.service.AbstractRestSampler.initAdHocInitialIndividuals(AbstractRestSampler.kt:102)
        at org.evomaster.core.problem.rest.service.AbstractRestSampler.initForBlackBox(AbstractRestSampler.kt:163)
        at org.evomaster.core.problem.rest.service.AbstractRestSampler.initialize(AbstractRestSampler.kt:45)
        at com.netflix.governator.lifecycle.LifecycleMethods.methodInvoke(LifecycleMethods.java:313)
`

**Comment by arcuri82** [comment]
Hi. 
  thanks for reporting this issue. It looks like a bug in the handling of regex in the `pattern` constraint. But, to properly debug it, we need to know the source regex that breaks it.

Could you be able to share your OpenAPI/Swagger file? If not, could you at least share all the `pattern` [declarations](https://swagger.io/docs/specification/data-models/data-types/#pattern)?

**Comment by lin2020** [comment]
Thanks.
I have solved this problem!

**Comment by arcuri82** [comment]
hi. there is still a bug... even if the schema was wrongly formatted, EM should still not crash like this.

could you be so kind to describe what you did? (eg, did u just remove the `pattern` constraints from the schema?)

**Comment by lin2020** [comment]
hi, i just remove the pattern constraints to avoid this error.

**Comment by arcuri82** [comment]
hi.
  could you post here such constraint? 
if it is sensitive, could you at least post an equivalent / redacted one for which the same issue arises?
thanks

**Comment by arcuri82** [comment]
This issue should now be fixed in the new 1.4.0 release
