### ISSUE TITLE
Failed to start the evomaster1.3.0.

### ISSUE THREAD

**Issue by Minju-Kan** [EMResearch/EvoMaster#467]
Hello,
I watched your video about writing a white box test driver and ran a project called Rest-api-example and it worked!
Then I tried to replace it with an open source SUT, which uses Spring Boot and H2 database.
I am using EvoMaster version: 1.3.0, then I have started the driver before running evomaster1.3.0.jar.
The driver runs successfully, but when I run evomaster1.3.0.jar I get the following error message:

```
 This is likely a bug in EvoMaster. Please copy&paste the following stacktrace, and create a new issue on ?[34mhttps://github.com/EMResearch/EvoMaster/issues?[0m?[0m
java.lang.reflect.InvocationTargetException: invokedynamic: method=public void org.evomaster.core.problem.rest.service.AbstractRestS
ampler.initialize(), target=org.evomaster.core.problem.rest.service.ResourceSampler@7bb35cc6
        at com.netflix.governator.lifecycle.LifecycleMethods.methodInvoke(LifecycleMethods.java:316)
        at com.netflix.governator.lifecycle.LifecycleMethods.methodInvoke(LifecycleMethods.java:298)
        at com.netflix.governator.lifecycle.LifecycleManager.startInstance(LifecycleManager.java:266)
        at com.netflix.governator.lifecycle.LifecycleManager.add(LifecycleManager.java:175)
        at com.netflix.governator.guice.InternalLifecycleModule.onProvision(InternalLifecycleModule.java:81)
        at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:117)
        at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:66)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:93)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:296)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
        at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:60)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
        at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:213)
        at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:186)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:113)
        at com.google.inject.internal.InjectorImpl.createChildInjector(InjectorImpl.java:239)
        at com.netflix.governator.guice.LifecycleInjector.createChildInjector(LifecycleInjector.java:331)
        at com.netflix.governator.guice.LifecycleInjector.createInjector(LifecycleInjector.java:411)
        at com.netflix.governator.guice.LifecycleInjector.createInjector(LifecycleInjector.java:352)
        at org.evomaster.core.Main$Companion.init(Main.kt:284)
        at org.evomaster.core.Main$Companion.initAndRun(Main.kt:138)
        at org.evomaster.core.Main$Companion.main(Main.kt:71)
        at org.evomaster.core.Main.main(Main.kt)
Caused by: java.lang.NullPointerException: schema must not be null
        at org.evomaster.core.problem.rest.OpenApiAccess.getOpenApi(OpenApiAccess.kt:28)
        at org.evomaster.core.problem.rest.OpenApiAccess.getOpenAPIFromURL(OpenApiAccess.kt:40)
        at org.evomaster.core.problem.rest.service.AbstractRestSampler.initialize(AbstractRestSampler.kt:66)
        at com.netflix.governator.lifecycle.LifecycleMethods.methodInvoke(LifecycleMethods.java:313)
        ... 26 common frames omitted

```
Thank you and have a nice day.

**Comment by arcuri82** [comment]
Hi,
  thx for your interest in EM.
It looks like there is an issue in the OpenAPI/Swagger schema you are using, but EM is swallowing the error message.

Until we fix the logs and make a new release, I suggest the following:

- update clinet-java to version 1.4.0
- clone the repository
- in an IDE (eg IntelliJ or Eclipse) start EM directly from the class `core/src/main/kotlin/org/evomaster/core/Main.kt`
- run EM in debug mode, and put a break point at line 24 in the class `core/src/main/kotlin/org/evomaster/core/problem/rest/OpenApiAccess.kt`
- with debugger, see the content of `messages` in `SwaggerParseResult` to see what issues your schema has
