### ISSUE TITLE
CycleObjectGene has no value

### ISSUE THREAD

**Issue by jose** [EMResearch/EvoMaster#489]
Hi @arcuri82,

Latest version of EvoMaster (i.e., v1.4.1-SNAPSHOT, commit [46661ff](https://github.com/EMResearch/EvoMaster/commit/46661fffb43e2937e170ecc7f442e549fd9fc6c2)) is throwing a `java.lang.IllegalStateException: CycleObjectGene has no value` when executed on the `patio-api` program.

Please find below the set of commands I'm currently using to run EvoMaster on the `patio-api` program and the SUT's and EvoMaster's log.

#### Commands to reproduce the unexpected exception

```bash

# TODO the following env variables must be updated to your machine
export EVOMASTER_AGENT_JAR_FILE_PATH="/tmp/emb/dist/evomaster-agent.jar"
export EVOMASTER_JAR_FILE_PATH="/tmp/evomaster/core/target/evomaster.jar"
export SUT_EM_JAR_FILE="/tmp/emb/dist/patio-api-evomaster-runner.jar"
export SUT_SUT_JAR_FILE="/tmp/emb/dist/patio-api-sut.jar"

java -Xms1G -Xmx4G -Djava.io.tmpdir="/tmp/patio-api/0/tmp" \
  -Dem.muteSUT=true \
  -Devomaster.instrumentation.jar.path="$EVOMASTER_AGENT_JAR_FILE_PATH" \
  -jar "$SUT_EM_JAR_FILE" \
  "10030" "10031" \
  "$SUT_SUT_JAR_FILE" \
  "120" \
  "/tmp/jdk-11/bin/java" &

CONTROLLER_PID="$!"
sleep 20s

java -Xms2G -Xmx4G -Djava.io.tmpdir="/tmp/patio-api/0/tmp" \
  -jar "$EVOMASTER_JAR_FILE_PATH" \
  --stoppingCriterion=TIME \
  --maxTime="60m" \
  --statisticsColumnId="patio-api" \
  --seed="0" \
  --sutControllerHost="localhost" \
  --sutControllerPort="10030" \
  --outputFolder="/tmp/patio-api/0/tests" \
  --statisticsFile="/tmp/patio-api/0/reports/statistics.csv" \
  --exportCoveredTarget=true \
  --coveredTargetFile="/tmp/patio-api/0/reports/coveredTargets.txt" \
  --writeStatistics=true \
  --showProgress=false \
  --testSuiteSplitType=NONE

kill "$CONTROLLER_PID"
```

#### SUT's log

```
2022-04-06 13:09:48.356:INFO::main: Logging initialized @750ms to shaded.org.eclipse.jetty.util.log.StdErrLog
2022-04-06 13:09:48.453:WARN:soejsh.ContextHandler:main: s.o.e.j.s.ServletContextHandler@75437611{/,null,UNAVAILABLE} contextPath ends with /*
abr 06, 2022 1:09:49 DA TARDE shaded.org.glassfish.jersey.internal.inject.Providers checkProviderRuntime
WARNING: A provider org.evomaster.client.java.controller.internal.EMController registered in SERVER runtime does not implement any provider interfaces applicable in the SERVER runtime. Due to constraint configuration problems the provider org.evomaster.client.java.controller.internal.EMController will be ignored.
abr 06, 2022 1:09:49 DA TARDE shaded.org.glassfish.jersey.internal.Errors logErrors
WARNING: The following warnings have been detected: WARNING: The (sub)resource method getWarning in org.evomaster.client.java.controller.internal.EMController contains empty path annotation.

Started controller server on: http://localhost:10030/controller/api
Going to start the SUT
13:10:10.453 [qtp1234250905-13] INFO  o.t.d.DockerClientProviderStrategy - Loaded org.testcontainers.dockerclient.UnixSocketClientProviderStrategy from ~/.testcontainers.properties, will try it first
13:10:11.524 [qtp1234250905-13] INFO  o.t.d.DockerClientProviderStrategy - Found Docker environment with local Unix socket (unix:///var/run/docker.sock)
13:10:11.527 [qtp1234250905-13] INFO  o.testcontainers.DockerClientFactory - Docker host IP address is localhost
13:10:11.576 [qtp1234250905-13] INFO  o.testcontainers.DockerClientFactory - Connected to docker:
  Server Version: 20.10.7
  API Version: 1.41
  Operating System: Ubuntu 20.04.1 LTS
  Total Memory: 24074 MB
13:10:11.581 [qtp1234250905-13] INFO  o.t.utility.ImageNameSubstitutor - Image name substitution will be performed by: DefaultImageNameSubstitutor (composite of 'ConfigurationFileImageNameSubstitutor' and 'PrefixingImageNameSubstitutor')
13:10:11.697 [qtp1234250905-13] INFO  o.t.utility.RegistryAuthLocator - Failure when attempting to lookup auth config. Please ignore if you don't have images in an authenticated registry. Details: (dockerImageName: testcontainers/ryuk:0.3.1, configFile: /home/jcmcampos/.docker/config.json. Falling back to docker-java default behaviour. Exception message: /home/jcmcampos/.docker/config.json (No such file or directory)
13:10:12.790 [qtp1234250905-13] INFO  o.testcontainers.DockerClientFactory - Ryuk started - will monitor and terminate Testcontainers containers on JVM exit
13:10:12.790 [qtp1234250905-13] INFO  o.testcontainers.DockerClientFactory - Checking the system...
13:10:12.791 [qtp1234250905-13] INFO  o.testcontainers.DockerClientFactory - ✔︎ Docker server version should be at least 1.6.0
13:10:12.898 [qtp1234250905-13] INFO  o.testcontainers.DockerClientFactory - ✔︎ Docker environment should have more than 2GB free disk space
13:10:12.953 [qtp1234250905-13] INFO  🐳 [postgres:9] - Creating container for image: postgres:9
13:10:13.063 [qtp1234250905-13] INFO  🐳 [postgres:9] - Starting container with ID: 5c8bdaf4361f041a5f848a23aa04dec1835b1c5f8caab2f32950636e04a20ccd
13:10:13.774 [qtp1234250905-13] INFO  🐳 [postgres:9] - Container postgres:9 is starting: 5c8bdaf4361f041a5f848a23aa04dec1835b1c5f8caab2f32950636e04a20ccd
13:10:13.796 [qtp1234250905-13] INFO  🐳 [postgres:9] - Container postgres:9 started in PT0.89635S
Going to start SUT with command:
/tmp/jdk-11/bin/java -Devomaster.javaagent.external.port=43179 -javaagent:/tmp/emb/dist/evomaster-agent.jar=patio. -Xmx2G -Xms1G -jar /tmp/emb/dist/patio-api-sut.jar -micronaut.server.port=10031 -datasources.default.url=jdbc:postgresql://localhost:49170/patio
Process output has been closed
```

#### EM's log

```
*
 _____          ___  ___          _
|  ___|         |  \/  |         | |
| |____   _____ | .  . | __ _ ___| |_ ___ _ __
|  __\ \ / / _ \| |\/| |/ _` / __| __/ _ \ '__|
| |___\ V / (_) | |  | | (_| \__ \ ||  __/ |
\____/ \_/ \___/\_|  |_/\__,_|___/\__\___|_|

* EvoMaster version: 1.4.1-SNAPSHOT
* WARNING: The option to turn on Executive Summary is only meaningful when clustering is turned on (--testSuiteSplitType CLUSTERING). The option has been deactivated for this run, to prevent a crash.
* Starting to generate test cases
* [ERROR] EvoMaster process terminated abruptly. This is likely a bug in EvoMaster. Please copy&paste the following stacktrace, and create a new issue on https://github.com/EMResearch/EvoMaster/issues
java.lang.IllegalStateException: CycleObjectGene has no value
        at org.evomaster.core.search.gene.CycleObjectGene.getValueAsPrintableString(CycleObjectGene.kt:39)
        at org.evomaster.core.search.gene.TupleGene.getValueAsPrintableString(TupleGene.kt:120)
        at org.evomaster.core.search.gene.ObjectGene.handleBooleanSelectionMode(ObjectGene.kt:304)
        at org.evomaster.core.search.gene.ObjectGene.getValueAsPrintableString(ObjectGene.kt:140)
        at org.evomaster.core.search.gene.ObjectGene.handleBooleanSelectionMode(ObjectGene.kt:308)
        at org.evomaster.core.search.gene.ObjectGene.getValueAsPrintableString(ObjectGene.kt:140)
        at org.evomaster.core.search.gene.ObjectGene.handleBooleanSelectionMode(ObjectGene.kt:308)
        at org.evomaster.core.search.gene.ObjectGene.getValueAsPrintableString(ObjectGene.kt:140)
        at org.evomaster.core.search.gene.Gene.getValueAsPrintableString$default(Gene.kt:218)
        at org.evomaster.core.problem.graphql.GraphQLUtils.getMutation(GraphQLUtils.kt:147)
        at org.evomaster.core.problem.graphql.GraphQLUtils.generateGQLBodyEntity(GraphQLUtils.kt:131)
        at org.evomaster.core.problem.graphql.service.GraphQLFitness.createInvocation(GraphQLFitness.kt:405)
        at org.evomaster.core.problem.graphql.service.GraphQLFitness.handleGraphQLCall(GraphQLFitness.kt:285)
        at org.evomaster.core.problem.graphql.service.GraphQLFitness.doCalculateCoverage(GraphQLFitness.kt:60)
        at org.evomaster.core.problem.graphql.service.GraphQLFitness.doCalculateCoverage(GraphQLFitness.kt:27)
        at org.evomaster.core.search.service.FitnessFunction.calculateIndividualWithPostHandling(FitnessFunction.kt:104)
        at org.evomaster.core.search.service.FitnessFunction.calculateCoverage(FitnessFunction.kt:56)
        at org.evomaster.core.search.service.mutator.Mutator.mutateAndSave(Mutator.kt:151)
        at org.evomaster.core.search.algorithms.MioAlgorithm.searchOnce(MioAlgorithm.kt:51)
        at org.evomaster.core.search.service.SearchAlgorithm.search(SearchAlgorithm.kt:66)
        at org.evomaster.core.Main$Companion.run(Main.kt:431)
        at org.evomaster.core.Main$Companion.initAndRun(Main.kt:149)
        at org.evomaster.core.Main$Companion.main(Main.kt:73)
        at org.evomaster.core.Main.main(Main.kt)
```

Other important info:
- OS: `Linux Ubuntu 20.04.1 LTS`
- JVM: `openjdk 11.0.9.1 2020-11-04`
- Docker: `version 20.10.7, build 20.10.7-0ubuntu5~20.04.2`

**Comment by arcuri82** [comment]
Hi.
  thx for reporting this bug. Support for GraphQL is still not fully stable, and it is going through some major refactoring.

@asmab89 when you have time, can you look at this?

**Comment by jose** [comment]
Thanks.  In your opinion, should we ignore all Java GraphQL's programs in the [EM benchmark](https://github.com/EMResearch/EMB) (i.e., `petclinic`, `patio-api`, `timbuctoo`, `graphql-ncs`, `graphql-scs`, and `ocvn-rest`) in any evaluation, at least for now?
I haven't got any other unexpected exception on any other program but `patio-api` though.

**Comment by arcuri82** [comment]
hi. yep, please ignore those GraphQL APIs for now, as it is work in progress.
However, should be no problem for `ocvn-rest` (although EM crashes on it using `1.4.0`, albeit SNAPSHOT is fine)
