### ISSUE TITLE
Create a New Project in Java

### ISSUE THREAD

**Issue by agrawalhemant5393** [EMResearch/EvoMaster#627]
I want to create a new project in Java. I am using your project of  rest-api-docs but getting multiple errors. I want to start without error with some helpful swagger api sample. I had tried updating pom.xml but it didn't worked. It will be helpful if you can create some clear tutorial with updated samples

**Comment by arcuri82** [comment]
hi.
  what errors do you get? the examples should be updated to latest `1.5.0` version. what discrepancies do you see?

**Comment by arcuri82** [comment]
`java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException`  look like you are trying to run an application that uses XML, but with a JDK after 8 (XML was removed from version 9 on, need to be added manually)

note that https://github.com/EMResearch/rest-api-example   explicitly states `It requires JDK 8`. Which JDK are u using? 
I guess we could make an example for latest LTS, ie 17

**Comment by agrawalhemant5393** [comment]
``` Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2022-10-26 11:08:13.802 ERROR 21156 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'itemRepository' defined in org.example.ItemRepository defined in @EnableJpaRepositories declared on JpaRepositoriesRegistrar.EnableJpaRepositoriesConfiguration: Cannot resolve reference to bean 'jpaMappingContext' while setting bean property 'mappingContext'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jpaMappingContext': Invocation of init method failed; nested exception is java.lang.IllegalStateException: Failed to asynchronously initialize native EntityManagerFactory: java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:342) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:113) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1697) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1442) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:593) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
```


Updated it to Java 8 still getting this error

**Comment by arcuri82** [comment]
closed due to https://github.com/EMResearch/rest-api-example/issues/1
