### ISSUE TITLE
EvoMaster core dump with error "Unrecognized mode:TEXT"

### ISSUE THREAD

**Issue by Hannah516** [EMResearch/EvoMaster#751]
Step:
1. download the latest EVOMaster Jar (2023/04/19)
2. Write a swagger yaml file of my project.(Only some simple API)
3. Run D:\TEST\EvoMaster-master>java -jar evomaster.jar --blackBox true --bbSwaggerUrl file:///D:/TEST/EvoMaster-master/simple.yaml --outputFormat JAVA_JUNIT_4 --maxTime 30s --ratePerMinute 60
in windows 10, java 1.8.0_311
5. There come out a core dump 

* Starting to generate test cases

[1A[2K* Consumed search budget: 24.343%; covered targets: 0; time per test: 7299.0ms (8.0 actions)
[1A[2K* Consumed search budget: 47.637%; covered targets: 9; time per test: 7140.0ms (7.5 actions)
[1A[2K* Consumed search budget: 54.323%; covered targets: 9; time per test: 5426.0ms (5.7 actions)
[1A[2K* Consumed search budget: 80.983%; covered targets: 9; time per test: 6067.5ms (6.3 actions)
* [31m[ERROR] [0m[33mEvoMaster process terminated abruptly. This is likely a bug in EvoMaster. Please copy&paste the following stacktrace, and create a new issue on [34mhttps://github.com/EMResearch/EvoMaster/issues[0m[0m
java.lang.IllegalArgumentException: Unrecognized mode: TEXT
        at org.evomaster.core.search.gene.ObjectGene.getValueAsPrintableString(ObjectGene.kt:388)
        at org.evomaster.core.search.gene.Gene.getValueAsPrintableString$default(Gene.kt:676)
        at org.evomaster.core.problem.rest.service.AbstractRestFitness.createInvocation(AbstractRestFitness.kt:634)
        at org.evomaster.core.problem.rest.service.AbstractRestFitness.handleRestCall(AbstractRestFitness.kt:419)
        at org.evomaster.core.problem.rest.service.BlackBoxRestFitness.doCalculateCoverage(BlackBoxRestFitness.kt:59)
        at org.evomaster.core.problem.rest.service.BlackBoxRestFitness.doCalculateCoverage(BlackBoxRestFitness.kt:15)
        at org.evomaster.core.search.service.FitnessFunction.calculateIndividualWithPostHandling(FitnessFunction.kt:105)
        at org.evomaster.core.search.service.FitnessFunction.calculateCoverage(FitnessFunction.kt:57)
        at org.evomaster.core.search.service.FitnessFunction.calculateCoverage$default(FitnessFunction.kt:48)
        at org.evomaster.core.search.algorithms.RandomAlgorithm.searchOnce(RandomAlgorithm.kt:23)
        at org.evomaster.core.search.service.SearchAlgorithm.search(SearchAlgorithm.kt:66)
        at org.evomaster.core.Main$Companion.run(Main.kt:473)
        at org.evomaster.core.Main$Companion.initAndRun(Main.kt:158)
        at org.evomaster.core.Main$Companion.main(Main.kt:82)
        at org.evomaster.core.Main.main(Main.kt)

**Comment by Hannah516** [comment]
This is my first time to write an API swagger file, but the yaml seems run well here https://editor.swagger.io/?ref=geeek.
And I run the same cmd with the yaml file saved from https://editor.swagger.io/?ref=geeek, it works well and generate test cases successfully.

**Comment by arcuri82** [comment]
hi.
 thanks for reporting this bug. it is indeed a bug in EM. however, it might be due to some imprecision in your schema file. In particular, it seems like you have an object definition in a input payload, but the type is declared as plain text (or simply not declared at all).

Can you post your OpenAPI schema here?

**Comment by Hannah516** [comment]
> 

Sorry I cant post the file cause of our company security rules. But I deleted some warning lines in my schema file, now it can generate 3 test cases. Thanks very much. 
Another question is : is it necessary to offer a schema file in WhiteBox testing? cause I noticed this "**To test a RESTful API, in the the getProblemInfo(), you need to return an instance of the RestProblem class. Here, you need to specify where the OpenApi schema is found**" in the  https://github.com/EMResearch/EvoMaster/blob/master/docs/write_driver.md. In my situation, I don't have a full shema file of our project...
Also I wonder that whether the EvoMaster support flask framework and Electron framework? I did't see any info about flask in the guide.
Thank you^^

**Comment by arcuri82** [comment]
EM can only call what is in the schema. if schema is incomplete, then what not specified will not be tested.

Regarding other frameworks/languages, from the readme: 

> "Whitebox testing mode: can be used for APIs compiled to JVM (e.g., Java and Kotlin). EvoMaster analyses the bytecode of the tested applications, and uses several heuristics such as testability transformations and taint analysis to be able to generate more effective test cases. We support JDK 8 and the major LTS versions after that (currently JDK 17). Might work on other JVM versions, but we provide NO support for it. Note: there is initial support for other languages as well, like for example JavaScript/TypeScript, but they are not in a stable, feature-complete state yet."
