### ISSUE TITLE
mvn java run EMDriver error

### ISSUE THREAD

**Issue by alegonzalezz** [EMResearch/EvoMaster#870]
Hi,

I'm using J8 ,Maven 3.8.1, evomaster 2.0.0. I want to run EMDriver using org.codehaus.mojo:exec-maven-plugin:3.1.0.  I using the rest-api-example. when I run with mvn exec:java, fails with the next error:

` An exception occurred while executing the Java class.
[ERROR] Failed to apply bytecode instrumentation with JavaAgent.
[ERROR] If you are using JDK 11 or above, are you sure you added the following JVM option?       
[ERROR]  -Djdk.attach.allowAttachSelf=true
[ERROR] Also, if you are using JDK 17 or above, you also need the following:
[ERROR] --add-opens java.base/java.util.regex=ALL-UNNAMED --add-opens java.base/java.net=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED
[ERROR] This can also be set globally with the JDK_JAVA_OPTIONS environment variable.
[ERROR] See documentation at https://github.com/EMResearch/EvoMaster/blob/master/docs/jdks.md: java.lang.reflect.InvocationTargetException: Can't attach to this jvm. Add -javaagent:C:\Users\GMKtec\AppData\Local\Temp\javaagent.org.evomaster.client.java.instrumentation.InstrumentingAgent5377763223104925741.jar to the commandline: Agent JAR loaded but agent failed to initialize`

**Comment by alegonzalezz** [comment]
some mor info about the error:

`Exception in thread "Attach Listener" java.lang.ClassNotFoundException: org.evomaster.client.java.instrumentation.InstrumentingAgent
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:304)
        at sun.instrument.InstrumentationImpl.loadClassAndCallAgentmain(InstrumentationImpl.java:411)`

**Comment by arcuri82** [comment]
hi @alegonzalezz ,

  thanks for your interest in EvoMaster. The error message is telling what is wrong, and provides a link to where you can find more info. In particular, setting up `JDK_JAVA_OPTIONS` should fix your issue.

**Comment by alegonzalezz** [comment]
hi @arcuri82

I configurate the options but keep crashing in the same place

`org.evomaster.client.java.controller.InstrumentedSutStarter.loadAgent` 
`                AgentLoader.loadAgentClass(InstrumentingAgent.class.getName(), "foobar_packagenameshouldnotexist.");
`
I'm using 2 versions ( Java8 & Java11 ) in both the error is the same. 
I'm trying to execute mvn exec:java using org.codehaus.mojo:exec-maven-plugin:3.1.0 .

In windows throw me : Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: sun.tools.attach.WindowsVirtualMachine

in Mac throw me: java.io.IOException: Can not attach to current VM.

**Comment by arcuri82** [comment]
hi,
 if you did set up `JDK_JAVA_OPTIONS`, did you restart the IDE/console you used? environment variables are loaded at start of a process. changing them at runtime will not change current running processes (and child processes spawn from them).

also, regarding Java 8, are you using a JDK or a JRE?

**Comment by alegonzalezz** [comment]
I upgrade to J11

java -version 
NOTE: Picked up JDK_JAVA_OPTIONS: -Djdk.attach.allowAttachSelf=true
openjdk version "11.0.21" 2023-10-17 LTS
OpenJDK Runtime Environment Zulu11.68+17-CA (build 11.0.21+9-LTS)
OpenJDK 64-Bit Server VM Zulu11.68+17-CA (build 11.0.21+9-LTS, mixed mode)

mvn -v
NOTE: Picked up JDK_JAVA_OPTIONS: -Djdk.attach.allowAttachSelf=true
Apache Maven 3.9.4 (dfbb324ad4a7c8fb0bf182e6d91b0ae20e3d2dd9)
Maven home: /usr/local/Cellar/maven/3.9.4/libexec
Java version: 11.0.21, vendor: Azul Systems, Inc., runtime: /Users/alejandrogonzalez/.sdkman/candidates/java/11.0.21-zulu/zulu-11.jdk/Contents/Home
Default locale: es_419, platform encoding: US-ASCII
OS name: "mac os x", version: "12.5", arch: "x86_64", family: "mac"


`Exception in thread "Attach Listener" java.lang.ClassNotFoundException: org.evomaster.client.java.instrumentation.InstrumentingAgent
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:527)
        at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:431)
        at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallAgentmain(InstrumentationImpl.java:535)
Agent failed to start!
[WARNING] 
java.lang.RuntimeException: 
Failed to apply bytecode instrumentation with JavaAgent.
If you are using JDK 11 or above, are you sure you added the following JVM option?
 -Djdk.attach.allowAttachSelf=true 
Also, if you are using JDK 17 or above, you also need the following:
--add-opens java.base/java.util.regex=ALL-UNNAMED --add-opens java.base/java.net=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED
This can also be set globally with the JDK_JAVA_OPTIONS environment variable.
See documentation at https://github.com/EMResearch/EvoMaster/blob/master/docs/jdks.md
    at org.evomaster.client.java.controller.InstrumentedSutStarter.loadAgent (InstrumentedSutStarter.java:48)
    at org.evomaster.client.java.controller.InstrumentedSutStarter.<init> (InstrumentedSutStarter.java:71)
    at org.evomaster.EMDriver.main (EMDriver.java:28)
    at org.codehaus.mojo.exec.ExecJavaMojo.lambda$execute$0 (ExecJavaMojo.java:283)
    at java.lang.Thread.run (Thread.java:829)
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
    at shaded.com.ea.agentloader.AgentLoader$1.loadAgent (AgentLoader.java:244)
    at shaded.com.ea.agentloader.AgentLoader.loadAgent (AgentLoader.java:77)
    at shaded.com.ea.agentloader.AgentLoader.loadAgentClass (AgentLoader.java:148)
    at shaded.com.ea.agentloader.AgentLoader.loadAgentClass (AgentLoader.java:102)
    at org.evomaster.client.java.controller.InstrumentedSutStarter.loadAgent (InstrumentedSutStarter.java:46)
    at org.evomaster.client.java.controller.InstrumentedSutStarter.<init> (InstrumentedSutStarter.java:71)
    at org.evomaster.EMDriver.main (EMDriver.java:28)
    at org.codehaus.mojo.exec.ExecJavaMojo.lambda$execute$0 (ExecJavaMojo.java:283)
    at java.lang.Thread.run (Thread.java:829)
Caused by: java.lang.reflect.InvocationTargetException
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at shaded.com.ea.agentloader.AgentLoader$1.loadAgent (AgentLoader.java:240)
    at shaded.com.ea.agentloader.AgentLoader.loadAgent (AgentLoader.java:77)
    at shaded.com.ea.agentloader.AgentLoader.loadAgentClass (AgentLoader.java:148)
    at shaded.com.ea.agentloader.AgentLoader.loadAgentClass (AgentLoader.java:102)
    at org.evomaster.client.java.controller.InstrumentedSutStarter.loadAgent (InstrumentedSutStarter.java:46)
    at org.evomaster.client.java.controller.InstrumentedSutStarter.<init> (InstrumentedSutStarter.java:71)
    at org.evomaster.EMDriver.main (EMDriver.java:28)
    at org.codehaus.mojo.exec.ExecJavaMojo.lambda$execute$0 (ExecJavaMojo.java:283)
    at java.lang.Thread.run (Thread.java:829)
Caused by: java.lang.RuntimeException: Can't attach to this jvm. Add -javaagent:/var/folders/4h/ld2kql6d27j02_r6mjb_2q_c0000gp/T/javaagent.org.evomaster.client.java.instrumentation.InstrumentingAgent10975760189149410064.jar to the commandline
    at shaded.com.ea.agentloader.AgentLoaderHotSpot.loadAgent (AgentLoaderHotSpot.java:74)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at shaded.com.ea.agentloader.AgentLoader$1.loadAgent (AgentLoader.java:240)
    at shaded.com.ea.agentloader.AgentLoader.loadAgent (AgentLoader.java:77)
    at shaded.com.ea.agentloader.AgentLoader.loadAgentClass (AgentLoader.java:148)
    at shaded.com.ea.agentloader.AgentLoader.loadAgentClass (AgentLoader.java:102)
    at org.evomaster.client.java.controller.InstrumentedSutStarter.loadAgent (InstrumentedSutStarter.java:46)
    at org.evomaster.client.java.controller.InstrumentedSutStarter.<init> (InstrumentedSutStarter.java:71)
    at org.evomaster.EMDriver.main (EMDriver.java:28)
    at org.codehaus.mojo.exec.ExecJavaMojo.lambda$execute$0 (ExecJavaMojo.java:283)
    at java.lang.Thread.run (Thread.java:829)
Caused by: com.sun.tools.attach.AgentInitializationException: Agent JAR loaded but agent failed to initialize
    at sun.tools.attach.HotSpotVirtualMachine.loadAgent (HotSpotVirtualMachine.java:165)
    at shaded.com.ea.agentloader.AgentLoaderHotSpot.loadAgent (AgentLoaderHotSpot.java:65)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at shaded.com.ea.agentloader.AgentLoader$1.loadAgent (AgentLoader.java:240)
    at shaded.com.ea.agentloader.AgentLoader.loadAgent (AgentLoader.java:77)
    at shaded.com.ea.agentloader.AgentLoader.loadAgentClass (AgentLoader.java:148)
    at shaded.com.ea.agentloader.AgentLoader.loadAgentClass (AgentLoader.java:102)
    at org.evomaster.client.java.controller.InstrumentedSutStarter.loadAgent (InstrumentedSutStarter.java:46)
    at org.evomaster.client.java.controller.InstrumentedSutStarter.<init> (InstrumentedSutStarter.java:71)
    at org.evomaster.EMDriver.main (EMDriver.java:28)
    at org.codehaus.mojo.exec.ExecJavaMojo.lambda$execute$0 (ExecJavaMojo.java:283)
    at java.lang.Thread.run (Thread.java:829)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  6.731 s
[INFO] Finished at: 2023-12-24T15:20:46-03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:3.1.1:java (default-cli) on project rest-api-example: An exception occurred while executing the Java class. 
[ERROR] Failed to apply bytecode instrumentation with JavaAgent.
[ERROR] If you are using JDK 11 or above, are you sure you added the following JVM option?
[ERROR]  -Djdk.attach.allowAttachSelf=true 
[ERROR] Also, if you are using JDK 17 or above, you also need the following:
[ERROR] --add-opens java.base/java.util.regex=ALL-UNNAMED --add-opens java.base/java.net=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED
[ERROR] This can also be set globally with the JDK_JAVA_OPTIONS environment variable.
[ERROR] See documentation at https://github.com/EMResearch/EvoMaster/blob/master/docs/jdks.md: java.lang.reflect.InvocationTargetException: Can't attach to this jvm. Add -javaagent:/var/folders/4h/ld2kql6d27j02_r6mjb_2q_c0000gp/T/javaagent.org.evomaster.client.java.instrumentation.InstrumentingAgent10975760189149410064.jar to the commandline: Agent JAR loaded but agent failed to initialize
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException`

**Comment by arcuri82** [comment]
hi,

 when you wrote: `I want to run EMDriver using org.codehaus.mojo:exec-maven-plugin:3.1.0`, how did you run it exactly? and what configuration of the plugin did you use? 

if you made changes to the pom (eg to setup the plugin), do you a have a forked repository you can share? so I can try to reproduce the issue

**Comment by arcuri82** [comment]
btw, does it work for you if you run `EMDriver` directly from an IDE? (eg IntelliJ or Eclispe)

**Comment by alegonzalezz** [comment]
Hi @arcuri82 

Yes I tried this is my repository: https://github.com/alegonzalezz/tesis_evomaster/tree/feat/run_test_and_evomaster

I'm using evomaster 2.0.0, I run the exec maven plugin with `mvn exec:java`

I run the EMDriver with the ide and i can run evomaster plugin.

thank you for the help

**Comment by arcuri82** [comment]
hi, 
 if I try to run that, I get:

```
mvn exec:java
NOTE: Picked up JDK_JAVA_OPTIONS: -Djdk.attach.allowAttachSelf=true --add-opens java.base/java.util.regex=ALL-UNNAMED --add-opens java.base/java.net=A
LL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED
[INFO] Scanning for projects...
[INFO]
[INFO] -------------------< org.evomaster:rest-api-example >-------------------
[INFO] Building rest-api-example 1.0.0-SNAPSHOT
[INFO]   from pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- exec:3.0.0:java (default-cli) @ rest-api-example ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.161 s
[INFO] Finished at: 2024-01-02T15:18:46+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:3.0.0:java (default-cli) on project rest-api-example: The parameters 'mainClass' fo
r goal org.codehaus.mojo:exec-maven-plugin:3.0.0:java are missing or invalid -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginParameterException
```

problem is that exec plugin is not configured: `The parameters 'mainClass' for goal org.codehaus.mojo:exec-maven-plugin:3.0.0:java are missing or invalid `

**Comment by arcuri82** [comment]
Dear @alegonzalezz ,

  thanks for trying out EvoMaster and opening an issue here. If you have 10 minutes, we would be grateful if you could fill this survey on test naming strategies #1206. We will use such information to improve EvoMaster. Thanks!
