### ISSUE TITLE
failed attempt grapghql JS_JEST blackbox

### ISSUE THREAD

**Issue by khalilos95** [EMResearch/EvoMaster#871]
evomaster.exe --maxTime 8h --outputFolder "noneedtoshare" --outputFilePrefix sevi --outputFormat JS_JEST --blackBox true --problemType GRAPHQL   --bbTargetUrl "noneedtoshare/graphql" --ratePerMinute 3

* Fetched GraphQL schema in 2152ms
* Fetched GraphQL schema in 563ms
* ←[31m[ERROR] ←[0m←[33mEvoMaster process terminated abruptly. This is likely a bug in EvoMaster. Please copy&paste the following stacktrace, and create a new issue on ←[34mhttps://github.com/EMResearch/EvoMaster/issues←[0m←[0m
java.lang.reflect.InvocationTargetException: invokedynamic: method=public void org.evomaster.core.problem.graphql.service.GraphQLSampler.initialize(), target=org.evomaster.core.problem.graphql.service.GraphQLSampler@3f049056
        at com.netflix.governator.lifecycle.LifecycleMethods.methodInvoke(LifecycleMethods.java:316)
        at com.netflix.governator.lifecycle.LifecycleMethods.methodInvoke(LifecycleMethods.java:298)
        at com.netflix.governator.lifecycle.LifecycleManager.startInstance(LifecycleManager.java:266)
        at com.netflix.governator.lifecycle.LifecycleManager.add(LifecycleManager.java:175)
        at com.netflix.governator.guice.InternalLifecycleModule.onProvision(InternalLifecycleModule.java:81)
        at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:117)
        at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:66)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:93)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:296)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
        at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:60)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:169)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:45)
        at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:213)
        at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:186)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:113)
        at com.google.inject.internal.InjectorImpl.createChildInjector(InjectorImpl.java:239)
        at com.netflix.governator.guice.LifecycleInjector.createChildInjector(LifecycleInjector.java:331)
        at com.netflix.governator.guice.LifecycleInjector.createInjector(LifecycleInjector.java:411)
        at com.netflix.governator.guice.LifecycleInjector.createInjector(LifecycleInjector.java:352)
        at org.evomaster.core.Main$Companion.init(Main.kt:385)
        at org.evomaster.core.Main$Companion.initAndRun(Main.kt:160)
        at org.evomaster.core.Main$Companion.main(Main.kt:84)
        at org.evomaster.core.Main.main(Main.kt)
Caused by: java.lang.StackOverflowError: null
        at org.evomaster.core.problem.graphql.builder.Table.copy(Table.kt)
        at org.evomaster.core.problem.graphql.builder.Table.copy$default(Table.kt)
        at org.evomaster.core.problem.graphql.builder.GraphQLActionBuilder.copyTableElement(GraphQLActionBuilder.kt:671)
        at

**Comment by arcuri82** [comment]
thanks for reporting this bug

**Comment by arcuri82** [comment]
Dear @khalilos95 ,

  thanks for trying out EvoMaster and opening an issue here. If you have 10 minutes, we would be grateful if you could fill this survey on test naming strategies #1206. We will use such information to improve EvoMaster. Thanks!
